timeout: 0
serial: yes
graphics: yes
default_entry: 1
quiet: no

/ZealOS aarch64 zealbooter
    protocol: limine
    path: boot():/boot/zealbooter.elf
    cmdline: zeal.plat=pi4
    module_path: boot():/boot/kernel.elf
    module_path: boot():/boot/demo.hcbc
    kaslr: no
    resolution: 800x600x32
